token: TOKEN # Bot token

embedColor: '#19AFFF'  # Colors for embed messages
commandPrefix: '!'  # Prefix for commands
owner: 'Ghexter'  # Who owns this bot

guildId: # Only register slash commands for the given guild.

# Command permissions
permissions:
  # Restrict commands for admin only (This is the script name)
  adminOnlyCommands:
    - 'stop'

  # Command for moderator with kick and ban perms (This is the script name)
  moderatorOnlyCommands: 
    - 'version'

# Slash commands
slashCommands:
  enabled: true

# Ignored channels based on IDs
blacklistChannels:            
  enabled: false  # Enable blacklisted channels

  # List of blacklisted channels
  channels: []
  convertToWhitelist: false  # Convert channels to whitelisted channels

# Custom bot presence
presence:
  enabled: true  # Enable presence
  status: ['online']  # Status of bot (online, idle, dnd, offline)  [this can be a string or an object for random value]
  type: ['playing']  # Type of status (playing, listening, watching, streaming) or enter a custom status  [this can be a string or an object for random value]
  activityName: ['Minecraft']  # Name your activity [this can be a string or an object for random value]

inviteFormat: https://discord.com/oauth2/authorize?client_id=%id%&permissions=8&scope=bot%20applications.commands   # Invite format for bot
language: 'config/language.yml'   # Langage file 
modulesFolder: 'modules'  # Define where's your modules

version: 1.3.1    # Version (don't modify this value)