error:
  - 'Error!'
  - 'An error!'
  - 'Error occurred'
  - 'POG error occured!'
empty:
  - 'Fill all required fields'
  - 'Don''t leave it'
  - 'Why empty fields'
needPing:
  - 'Ping someone!'
  - 'Ping someone!'
  - 'Ping someone! bruh'
thinking:
  - 'Thonking'
  - 'Thinking...'
  - 'Thonk... Thonk...'
  - 'Thonking...'
  - 'My brain is thinking...'
noPerms:
  - 'No perms!'
  - 'You don''t have permissions to do that!'
  - 'You don''t have perms'
  - 'LUL no perms!'
notAvailable:
  - 'This action is not available'
  - 'This is not available'
  - 'You can''t use this for now'
noResponse:
  - 'I got nothing for you'
  - 'Sorry, I don''t see anything for you'
  - 'I can''t get response for this'
success:
  - 'Successful!'
  - 'Successful'
  - 'Noice! It''s done'
tooLarge:
  - 'This is too large'
  - 'Too large for me'
  - ':eyes: can you make it smaller?'
tooSmall:
  - 'Too small!'
  - 'Too small'
  - 'So tiny for me'

# For commands
stop: 
  - 'Ok'
  - 'Shut up! I''ll stop now'
  - 'Ok bitch'
  - 'Stopping...'
help:
  title: 'Command Help'
  description: 'Here''s a list of the current commands:'

version: 1.3.1 # Version (don't modify this value)